// <auto-generated />
using System;
using API.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20240429044028_03")]
    partial class _03
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API.Enity.Exam", b =>
                {
                    b.Property<int>("ExamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ExamID"));

                    b.Property<string>("ExamDescription")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("ExamDuration")
                        .HasColumnType("time(6)");

                    b.Property<string>("Skill")
                        .HasColumnType("longtext");

                    b.HasKey("ExamID");

                    b.ToTable("exams");
                });

            modelBuilder.Entity("API.Enity.Practice", b =>
                {
                    b.Property<int>("PracticeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PracticeID"));

                    b.Property<int?>("Exam")
                        .HasColumnType("int");

                    b.Property<int?>("ExamID")
                        .HasColumnType("int");

                    b.Property<string>("PracticeDescription")
                        .HasColumnType("longtext");

                    b.HasKey("PracticeID");

                    b.HasIndex("ExamID");

                    b.ToTable("practices");
                });

            modelBuilder.Entity("API.Enity.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<string>("Answer1")
                        .HasColumnType("longtext");

                    b.Property<string>("Answer2")
                        .HasColumnType("longtext");

                    b.Property<string>("Answer3")
                        .HasColumnType("longtext");

                    b.Property<string>("Answer4")
                        .HasColumnType("longtext");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("longtext");

                    b.Property<string>("CorrectDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("QuestionContext")
                        .HasColumnType("longtext");

                    b.Property<int?>("Sentences")
                        .HasColumnType("int");

                    b.Property<int?>("sentencesSentenceId")
                        .HasColumnType("int");

                    b.HasKey("QuestionID");

                    b.HasIndex("sentencesSentenceId");

                    b.ToTable("questions");
                });

            modelBuilder.Entity("API.Enity.QuestionComplete", b =>
                {
                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("QuestionChoose")
                        .HasColumnType("longtext");

                    b.Property<int?>("SenComSentenceID")
                        .HasColumnType("int");

                    b.Property<int?>("Sentence")
                        .HasColumnType("int");

                    b.HasKey("QuestionID");

                    b.HasIndex("SenComSentenceID");

                    b.ToTable("questionCompletes");
                });

            modelBuilder.Entity("API.Enity.Result", b =>
                {
                    b.Property<int>("ResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ResultID"));

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<int?>("Sentence")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ResultID");

                    b.HasIndex("Sentence")
                        .IsUnique();

                    b.HasIndex("User")
                        .IsUnique();

                    b.ToTable("results");
                });

            modelBuilder.Entity("API.Enity.Sentence", b =>
                {
                    b.Property<int>("SentenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SentenceId"));

                    b.Property<string>("FilePath")
                        .HasColumnType("longtext");

                    b.Property<int?>("Practice")
                        .HasColumnType("int");

                    b.Property<int?>("PracticeID")
                        .HasColumnType("int");

                    b.HasKey("SentenceId");

                    b.HasIndex("PracticeID");

                    b.ToTable("sentences");
                });

            modelBuilder.Entity("API.Enity.SentenceComplete", b =>
                {
                    b.Property<int>("SentenceID")
                        .HasColumnType("int");

                    b.Property<int?>("Result")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<TimeSpan>("Totaltime")
                        .HasColumnType("time(6)");

                    b.Property<string>("User")
                        .HasColumnType("varchar(255)");

                    b.HasKey("SentenceID");

                    b.HasIndex("User")
                        .IsUnique();

                    b.ToTable("sentenceCompletes");
                });

            modelBuilder.Entity("API.Enity.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserID");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad376a8f-9eab-4bb9-9fca-30b01540f445",
                            Name = "admin",
                            NormalizedName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cdd31766-d8ae-4f0a-9bac-f14b1e8a0b2f",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "admin@gmail.com",
                            NormalizedUserName = "admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEFB6B7ITzRqJcM7aAYGhH6IoWBHfoszoNE5CgQmQMoRQ4+9DwRdt6VvEuDKVxGzDwQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            RoleId = "ad376a8f-9eab-4bb9-9fca-30b01540f445"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("API.Enity.Practice", b =>
                {
                    b.HasOne("API.Enity.Exam", "exam")
                        .WithMany("practices")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("exam");
                });

            modelBuilder.Entity("API.Enity.Question", b =>
                {
                    b.HasOne("API.Enity.Sentence", "sentences")
                        .WithMany("questions")
                        .HasForeignKey("sentencesSentenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("sentences");
                });

            modelBuilder.Entity("API.Enity.QuestionComplete", b =>
                {
                    b.HasOne("API.Enity.Question", "test")
                        .WithOne("quescom")
                        .HasForeignKey("API.Enity.QuestionComplete", "QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Enity.SentenceComplete", "SenCom")
                        .WithMany("QuestionCompletes")
                        .HasForeignKey("SenComSentenceID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SenCom");

                    b.Navigation("test");
                });

            modelBuilder.Entity("API.Enity.Result", b =>
                {
                    b.HasOne("API.Enity.SentenceComplete", "sentenceCom")
                        .WithOne("result")
                        .HasForeignKey("API.Enity.Result", "Sentence");

                    b.HasOne("API.Enity.User", "user")
                        .WithOne("result")
                        .HasForeignKey("API.Enity.Result", "User");

                    b.Navigation("sentenceCom");

                    b.Navigation("user");
                });

            modelBuilder.Entity("API.Enity.Sentence", b =>
                {
                    b.HasOne("API.Enity.Practice", "practice")
                        .WithMany("sentences")
                        .HasForeignKey("PracticeID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("practice");
                });

            modelBuilder.Entity("API.Enity.SentenceComplete", b =>
                {
                    b.HasOne("API.Enity.Sentence", "Sentence")
                        .WithOne("sencom")
                        .HasForeignKey("API.Enity.SentenceComplete", "SentenceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Enity.User", "user")
                        .WithOne("sencom")
                        .HasForeignKey("API.Enity.SentenceComplete", "User");

                    b.Navigation("Sentence");

                    b.Navigation("user");
                });

            modelBuilder.Entity("API.Enity.User", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "user")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Enity.Exam", b =>
                {
                    b.Navigation("practices");
                });

            modelBuilder.Entity("API.Enity.Practice", b =>
                {
                    b.Navigation("sentences");
                });

            modelBuilder.Entity("API.Enity.Question", b =>
                {
                    b.Navigation("quescom")
                        .IsRequired();
                });

            modelBuilder.Entity("API.Enity.Sentence", b =>
                {
                    b.Navigation("questions");

                    b.Navigation("sencom")
                        .IsRequired();
                });

            modelBuilder.Entity("API.Enity.SentenceComplete", b =>
                {
                    b.Navigation("QuestionCompletes");

                    b.Navigation("result");
                });

            modelBuilder.Entity("API.Enity.User", b =>
                {
                    b.Navigation("result")
                        .IsRequired();

                    b.Navigation("sencom")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
